version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
       # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: 
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependecies-{{ checksum "package.json"}}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy at netlify
          command: npm run deploy


workflows:
  build_test_deploy:
    jobs:
      - deploy